project:
  type: website

website:
  title: "group homepage"
  author: "shi_fazhen"
  date: "2025-4-23"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



