project:
  type: website

website:
  title: "山顶小纵队"
  navbar:
    left:
      - href: index.qmd
        text: 关于小纵队
      - href: members.qmd
        text: 成员介绍

format:
  html:
    theme:
      - lumen
    css: styles.css
    toc: true



